### PR TITLE
Add capture-kube command

### PR DESCRIPTION
**Pull request by carkmorwin**
Currently ships all logs under /var/log/containers to Timber platform.
Filtering will need to be added at the very least for the timber agent's
own logs.

### CODE REVIEW

**Comment by binarylogic** [comment]
I don't think you should address this now, but I'm concerned about the duplication in this file. The `runCaptureKube` function overlaps considerably with `runCaptureFiles` function. They should both call a shared function of some sort. If this is not addressed we should open an issue for it.

Also, for general house keeping, be sure to add a changelog addition.

**Comment by DavidAntaramian** [comment]
I agree about adding a CHANGELOG entry. As for DRY code, I think it may be a bit early in the process. Things could still change significantly.

**Comment by DavidAntaramian** [comment]
@carkmorwin Is this a first pass at the `capture-kube` command or will there be more work? The major issue I see here is the limitations in configuration options. I'm looking here specifically:

https://github.com/timberio/agent/pull/132/files#diff-7ddfb3e035b42cd70649cc33393fe32cR292

There's no ability for the end user to change the endpoint destination (which server to forward to) or the batch rate. I'd like to see those options supported before releasing this feature.

**Comment by carkmorwin** [comment]
@DavidAntaramian this is definitely a first pass at `capture-kube`. There is additional work that currently lives in other branches/PRs (#133 ) that builds on top of this, including config code. That being said, I can pull in config code here since it is the same as `capture-files`.

**Pull request merged**
