### PR TITLE
Fix failing aws_ec2_metadata tests

### PR DESCRIPTION
**Pull request by carkmorwin**

### CODE REVIEW

**Comment by DavidAntaramian** [comment]
These changes shouldn't be needed. The tests are specifically for the service not being available at all. In other words, these tests are for the condition where a connection to a remote peer cannot be established. If these tests are failing, then there should be a code change.

**Comment by DavidAntaramian** [comment]
@carkmorwin Got it. In that case, we need to make it use an address that shouldn't be responsive. I think changing `BaseEndpoint` to point to `http://127.0.0.1` should do it. The localhost shouldn't have anything listening.

The problem with your change is that you're creating a server which responds with 500 which is different than never being able to reach the server at all. We want to test the latter.

**Comment by carkmorwin** [comment]
@DavidAntaramian Got it, makes sense 👍

**Comment by carkmorwin** [comment]
@DavidAntaramian bump on this, just want to get a last check but should be inline with your comment.

**Pull request merged**
