### PR TITLE
By default, store statefiles in local statefiles dir

### PR DESCRIPTION
**Pull request by carkmorwin**
While ideally this is a configurable option, it would be helpful in a docker/kubernetes context to store statefiles in a directory. For now this would be a `statefiles` dir relative to the binary, which mostly preserves existing logic.

### CODE REVIEW

**Comment by DavidAntaramian** [comment]
So, first, the statefile is stored relative to the tailing target, not the binary. So if your target is `/var/log/nginx/access.log`, the statefile is `/var/log/nginx/access-state.json`. With your change, this will be `/var/log/nginx/statefiles/access-state.json`. Honestly, neither is very intuitive to me. I'm also concerned about what happens if the runtime permissions don't allow directory creation.

I'm thinking that the problem you're describing would be better addressed with a solution to #8, but that's a larger change than we should be working on right now.

**Comment by carkmorwin** [comment]
@DavidAntaramian Ok, thanks for clearing that up.

In that case, can we default to `/var/lib/timber`? This would then include changes to use the filename, and no the basepath, so files would be of the form `/var/lib/timber/file-state.json`. 

Also, in terms of permissions I'd be wary of writing state files next to the files themselves which is the current implementation. Unless we are defaulting to the root user (which may or may not be necessary), I feel like the agent would fail creating anything in `/var/log/`, file or directory.

Longer term yes I do want a bigger change. For now, I'm not sure how to handle keeping state in docker/kubernetes without having a known path where are the state files live that we can tied to a host path, and this is my quick and dirty solution.

**Comment by DavidAntaramian** [comment]
I agree with you in regards to permission. All of our installation instructions assume the agent is being run with root user permissions; ideally, though the agent should be able to run in a limited privilege situation.

The problem with changing the default now is that you'll need to implement upgrade logic that investigates previous possible locations so that existing users of the agent can upgrade without losing state. See my most recent comment on #8 which preempted your suggestions a bit.

**Comment by carkmorwin** [comment]
@DavidAntaramian good point. I'll have to think about this some more. Closing for now in favor of #8.

**Pull request closed without merging**
