### PR TITLE
Overhaul state to support flushing to disk on an interval

### PR DESCRIPTION
**Pull request by carkmorwin**
There are a number of hoops jumped through in these changes, but seemed
to be the simplest way to pass along the necessary information to save
state on successful send. Additionally, capture-files and capture-kube
have exit and blocking calls to be able to run commands on exit while
preserving our existing timeout.

### CODE REVIEW

**Comment by DavidAntaramian** [comment]
@carkmorwin Reading through this, I think I get the general premise of what's being done, but could you provide a more descriptive overview of how the architecture has changed? Additionally, I'd like to see more comments here about what's going on and how data is being passed around. I feel like we're approaching a point where it will be difficult to maintain this code. For example, you've added multiple new Go routines to the `forwarding.go` file, but there's no context about their responsibility.

**Comment by carkmorwin** [comment]
@DavidAntaramian I'll go drop in comments but basically we are intercepting adding code to sit in between the tailer, batcher, and forwarder. This is in order to grab and send the necessary metadata, which is really just filename and postition. 

The LogMessage interface is an attempt to be able to treat stdin log messages and file log messages the same way.

**Comment by carkmorwin** [comment]
@DavidAntaramian I pushed a bunch of commits that hopefully shed light on what I was thinking/what's going on. If not I can expand further.

**Comment by carkmorwin** [comment]
@DavidAntaramian Unless there are glaring issues or things that need explanation, I'd like to get this out this week to resolve our existing state issues. Refactoring/reworking logic can be done at another time.

**Comment by carkmorwin** [comment]
@DavidAntaramian changes have been made to the batcher to accept LogMessages which addresses the issues we discussed in person. Let me know if this is good to go, or if other changes are needed?

**Comment by DavidAntaramian** [comment]
This is way better than the multiple go routines you had before, though. Liking this a lot. It seems a lot easier to maintain and much less chance of any race conditions. 🙌

**Comment by carkmorwin** [comment]
@DavidAntaramian moving forward with this PR

**Comment by binarylogic** [comment]
Nice job, I think this solves our immediate concerns 👍 . A few things though:

1. How expensive is `tailer.tell()`? From [here](https://github.com/hpcloud/tail/blob/faf842bde7ed83bbc3c65a2c454fae39bc29a95f/tail.go#L142) it's unclear to me. But we're calling it on every line which is why I ask.
2. Ideally we'd be calling `tailer.tell()` when we checkpoint. I understand this is difficult with the way we have the goroutines structured which points to a larger design problem.
3. At some point we need to take a step back and look at the process as a whole and come up with a simpler design that also doesn't require calling `tell()` on every line. For example, maybe it makes more sense to define our own `Reader` interface with a `Checkpoint()` function. Then we'd just implement that interface for both file and `STDIN`. `Checkpoint` for `STDIN` would just be a NOOP.

Wanted to put that out there. Moving on!

**Comment by carkmorwin** [comment]
@binarylogic Agree with all of you points made here. `tailer.Tell()` results in a system call `seek` being made which sets and returns the byte position in a file. 
http://man7.org/linux/man-pages/man2/lseek.2.html

Afaict this is not an expensive operation, but is a syscall which we should be careful about making since this can probably cause issues over a certain threshold. I don't expect to be an issue based on current usage, but this should be squashed. 

At first glance, I don't think this would be hard to replace. We just need to verify if something like reading the length of the line we receive from the tailer is the same as what `Tell()` is returning.

**Comment by binarylogic** [comment]
Sounds good. And I don't think replacing `tell()` is the correct solution, the correct solution is only grabbing that information when we need it (during checkpointing). Instead of calling it once per line, call it once per batch.

**Comment by carkmorwin** [comment]
The problem will calling `tell()` or its equivalent during batch is that unless we know for certain the tailer is not reading in new lines, we cannot link the last message in the buffer with the last position of the tailer. This is created by the tailer, buffer, and forwarding all running in separate channels. 

Sending the position along with each line allows to know what position in the file is represented by line, and therefore the buffer.

**Pull request merged**
